name: Compression

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  process_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for upstream changes
        id: check_updates
        run: |
          CURRENT_COMMIT=$(git ls-remote https://github.com/borestad/blocklist-abuseipdb HEAD | cut -f1)
          if [ -f last_commit.txt ]; then
            LAST_COMMIT=$(cat last_commit.txt)
          else
            LAST_COMMIT=""
          fi
          echo "current_commit=$CURRENT_COMMIT" >> $GITHUB_OUTPUT
          echo "last_commit=$LAST_COMMIT" >> $GITHUB_OUTPUT
          if [ "$CURRENT_COMMIT" = "$LAST_COMMIT" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No upstream changes detected"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Upstream changes detected - updating last_commit.txt"
            echo "$CURRENT_COMMIT" > last_commit.txt
          fi

      - name: Set up Python
        if: steps.check_updates.outputs.has_changes == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install Dependencies
        if: steps.check_updates.outputs.has_changes == 'true'
        run: |
          pip install requests

      - name: Run the IP processing script
        if: steps.check_updates.outputs.has_changes == 'true'
        run: |
          python subnet_compressor.py

      - name: Cleanup downloads folder
        if: steps.check_updates.outputs.has_changes == 'true'
        run: |
          rm -rf downloads

      - name: Set commit message
        if: steps.check_updates.outputs.has_changes == 'true'
        id: commit_message
        run: |
          echo "COMMIT_MESSAGE=️️⚡️ SYNC ⚡️ $(date +'%Y/%m/%d %H:%M')" >> $GITHUB_ENV
      - name: Commit and push changes
        if: steps.check_updates.outputs.has_changes == 'true'
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout --orphan temp_branch
          git add -A
          git commit -m "${{ env.COMMIT_MESSAGE }}" || echo "No changes to commit"
          git branch -D main
          git branch -m main
          git push -f origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
